using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework;
using System.Diagnostics;

namespace HappyDungeon
{
    /// <summary>
    /// Display wrapper class.
    /// So that the Game1 class does not have to add all these fields. 
    /// 
    /// Despite having similar structure and interaction method, they are not implementation
    /// of any interface, since their goal and features are rather different. 
    /// 
    /// A thing about display is that all texts are generated by calling the textbridge,
    /// which returns texts depends on language setting, and then call fonts, which converts
    /// the texts into image/sprite/texture. 
    /// </summary>
    public class GeneralDisplay
    {

        private Game1 game;


        private UI.Displays.BagDisplay bagDisplay;
        private UI.Displays.TitleScreenDisplay titleDisplay;
        private UI.Displays.SettingDisplay settingDisplay;
        private UI.Displays.PauseDisplay pauseDisplay;
        private UI.Displays.GameOverDisplay gameOverDisplay;
        private UI.Displays.LoadAndSaveDisplay loadAndSaveDisplay;

        public GeneralDisplay(Game1 G)
        {
            game = G;


            InitDisplays();
        }

        private void InitDisplays()
        {
            bagDisplay = new UI.Displays.BagDisplay(game);
            titleDisplay = new UI.Displays.TitleScreenDisplay(game);
            settingDisplay = new UI.Displays.SettingDisplay(game);
            pauseDisplay = new UI.Displays.PauseDisplay(game);
            gameOverDisplay = new UI.Displays.GameOverDisplay(game);
            loadAndSaveDisplay = new UI.Displays.LoadAndSaveDisplay(game);
        }

        public void OptionMoveLeft()
        {
            switch (game.gameState)
            {
                case Globals.GameStates.Bag:
                    break;
                case Globals.GameStates.Setting:
                    settingDisplay.OptionMoveLeft();
                    break;
                default:
                    break;
            }
        }

        public void OptionMoveRight()
        {
            switch (game.gameState)
            {
                case Globals.GameStates.Bag:
                    break;
                case Globals.GameStates.Setting:
                    settingDisplay.OptionMoveRight();
                    break;
                default:
                    break;
            }
        }

        public void OptionMoveUp()
        {
            switch (game.gameState)
            {
                case Globals.GameStates.Bag:
                    break;
                case Globals.GameStates.TitleScreen:
                    titleDisplay.OptionMoveUp();
                    break;
                case Globals.GameStates.GameOver:
                    gameOverDisplay.OptionMoveUp();
                    break;
                case Globals.GameStates.Setting:
                    settingDisplay.OptionMoveUp();
                    break;
                case Globals.GameStates.Pause:
                    pauseDisplay.OptionMoveUp();
                    break;
                default:
                    break;
            }
        }

        public void OptionMoveDown()
        {
            switch (game.gameState)
            {
                case Globals.GameStates.Bag:
                    break;
                case Globals.GameStates.TitleScreen:
                    titleDisplay.OptionMoveDown();
                    break;
                case Globals.GameStates.GameOver:
                    gameOverDisplay.OptionMoveDown();
                    break;
                case Globals.GameStates.Setting:
                    settingDisplay.OptionMoveDown();
                    break;
                case Globals.GameStates.Pause:
                    pauseDisplay.OptionMoveDown();
                    break;
                default:
                    break;
            }
        }

        public void OptionConfirm()
        {
            switch (game.gameState)
            {
                case Globals.GameStates.Bag:
                    break;
                case Globals.GameStates.TitleScreen:
                    titleDisplay.OptionConfirm();
                    break;
                case Globals.GameStates.GameOver:
                    gameOverDisplay.OptionConfirm();
                    break;
                case Globals.GameStates.Setting:
                    settingDisplay.OptionConfirm();
                    break;
                case Globals.GameStates.Pause:
                    pauseDisplay.OptionConfirm();
                    break;
                default:
                    break;
            }
        }

        public void LeftClickRelease(Vector2 CursorPos)
        {
            switch (game.gameState)
            {
                case Globals.GameStates.Bag:
                    bagDisplay.LeftClickRelease(CursorPos);
                    break;
                case Globals.GameStates.TitleScreen:
                    titleDisplay.LeftClickRelease(CursorPos);
                    break;
                case Globals.GameStates.GameOver:
                    gameOverDisplay.LeftClickRelease(CursorPos);
                    break;
                case Globals.GameStates.Setting:
                    settingDisplay.LeftClickRelease(CursorPos);
                    break;
                case Globals.GameStates.LoadAndSave:
                    loadAndSaveDisplay.LeftClickRelease(CursorPos);
                    break; 
                case Globals.GameStates.Pause:
                    pauseDisplay.LeftClickRelease(CursorPos);
                    break;
                default:
                    break;
            }
        }

        public void LeftClickEvent(Vector2 CursorPos)
        {
            switch (game.gameState)
            {
                case Globals.GameStates.Bag:
                    bagDisplay.LeftClickEvent(CursorPos);
                    break;
                case Globals.GameStates.TitleScreen:
                    titleDisplay.LeftClickEvent(CursorPos);
                    break;
                case Globals.GameStates.GameOver:
                    gameOverDisplay.LeftClickEvent(CursorPos);
                    break;
                case Globals.GameStates.Setting:
                    settingDisplay.LeftClickEvent(CursorPos);
                    break;
                case Globals.GameStates.LoadAndSave:
                    loadAndSaveDisplay.LeftClickEvent(CursorPos);
                    break;
                case Globals.GameStates.Pause:
                    pauseDisplay.LeftClickEvent(CursorPos);
                    break;
                default:
                    break;
            }
        }

        /// <summary>
        /// Update cursor position mostly for on hover effects 
        /// </summary>
        /// <param name="CursorPos">Curosr position</param>
        public void UpdateCursorPos(Vector2 CursorPos)
        {
            switch (game.gameState)
            {
                case Globals.GameStates.Bag:
                    bagDisplay.UpdateOnhover(CursorPos);
                    break;
                case Globals.GameStates.TitleScreen:
                    titleDisplay.UpdateOnhover(CursorPos);
                    break;
                case Globals.GameStates.GameOver:
                    gameOverDisplay.UpdateOnhover(CursorPos);
                    break;
                case Globals.GameStates.Setting:
                    settingDisplay.UpdateOnhover(CursorPos);
                    break;
                case Globals.GameStates.LoadAndSave:
                    loadAndSaveDisplay.UpdateOnhover(CursorPos);
                    break;
                case Globals.GameStates.Pause:
                    pauseDisplay.UpdateOnhover(CursorPos);
                    break;
                default:
                    break;
            }
        }

        public void Update()
        {
            switch (game.gameState)
            {
                case Globals.GameStates.Bag:
                    bagDisplay.Update();
                    break;
                case Globals.GameStates.TitleScreen:
                    titleDisplay.Update();
                    break;
                case Globals.GameStates.Setting:
                    settingDisplay.Update();
                    break;
                case Globals.GameStates.Pause:
                    pauseDisplay.Update();
                    break;
                case Globals.GameStates.LoadAndSave:
                    loadAndSaveDisplay.Update();
                    break;
                case Globals.GameStates.GameOver:
                    gameOverDisplay.Update();
                    break;
                default:
                    break;
            }
        }

        public void Draw()
        {
            switch (game.gameState)
            {
                case Globals.GameStates.Bag:
                    bagDisplay.Draw();
                    break;
                case Globals.GameStates.TitleScreen:
                    titleDisplay.Draw();
                    break;
                case Globals.GameStates.Setting:
                    settingDisplay.Draw();
                    break;
                case Globals.GameStates.Pause:
                    pauseDisplay.Draw();
                    break;
                case Globals.GameStates.LoadAndSave:
                    loadAndSaveDisplay.Draw();
                    break; 
                case Globals.GameStates.GameOver:
                    gameOverDisplay.Draw();
                    break;
                default:
                    break; 
            }
        }



    }
}
